title: Janine Smith
email: justsingnmore@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
# so I can check it on my phone:
host: 0.0.0.0
port: 4000
env: prod